/**
 * Image blur placeholder data URLs (LQIP — Low Quality Image Placeholders).
 * Generated by scripts/optimize-images.mjs.
 *
 * Usage with next/image:
 *   <Image src={src} placeholder="blur" blurDataURL={BLUR_DATA_URLS[src]} />
 *
 * These tiny ~200-byte WebP images display instantly while the full image loads,
 * eliminating layout shift (CLS) and improving perceived performance dramatically.
 */

import manifest from "../../../public/images/optimized/manifest.json";

type ManifestEntry = {
  optimized: Record<string, string>;
  blurDataURL: string;
};

const typedManifest = manifest as Record<string, ManifestEntry>;

/**
 * Get the blur data URL for a given image path.
 * Returns undefined if no placeholder exists (safe fallback for next/image).
 */
export function getBlurDataURL(imagePath: string): string | undefined {
  return typedManifest[imagePath]?.blurDataURL;
}

/**
 * Get the optimized path for a given image at a target size.
 * Falls back to the original path if no optimized version exists.
 *
 * @param imagePath - Original image public path, e.g. "/images/members/1.png"
 * @param size - Target size: "sm" | "md" | "lg" | "xl" | "full"
 * @returns Optimized WebP path or original path
 */
export function getOptimizedImagePath(
  imagePath: string,
  size: "sm" | "md" | "lg" | "xl" | "full" = "full"
): string {
  const entry = typedManifest[imagePath];
  if (!entry) return imagePath;
  return entry.optimized[size] ?? entry.optimized.full ?? imagePath;
}

/**
 * Get all available optimized sizes for an image.
 * Useful for building srcset or responsive source elements.
 */
export function getOptimizedSizes(
  imagePath: string
): Record<string, string> | undefined {
  return typedManifest[imagePath]?.optimized;
}

/**
 * Video poster paths — pre-generated dark gradient posters
 * for instant visual display before video data loads.
 */
export const VIDEO_POSTERS = {
  hero: "/videos/posters/hero-video-poster.webp",
  banner: "/videos/posters/banner-poster.webp",
  info: "/videos/posters/info-poster.webp",
  programs: "/videos/posters/programs-poster.webp",
} as const;
